theme="vienna"
baseurl = "http://life-of-rpi.nikolaischlegel.com/"
languageCode = "en-us"
title = "Life of Raspberry PI"
MetaDataFormat = "toml"
copyright = "© 2016 Nikolai Schlegel"

[params]
    author = "Nikolai Schlegel"
    github = "huegli"
    linkedin = "nikolaischlegel"
    avatar = "/images/Avatar_Huegli.jpg"
    contact = "nikolai.schlegel@gmail.com"
    bio = "I like hacking around with Linux, Raspberry PI's and other Computer-related things in my precious spare time."
    subtitle = "All the fun things I do with and around Raspberry PI's"
[permalinks]
    post = "/:year/:month/:day/:filename/"
